### ISSUE TITLE
Bug when creating a Character Sheet

### ISSUE THREAD

**Issue by GreatKingCody** [LordAshes/TaleSpire-CharacterSheetsPlugin#1]
I am having an issue where I cannot create a character sheet from in game. 

Also, I don't think the Ctrl + I hotkey is used anymore, at least I cant customize it in R2modman. The stack trace is below:

```
[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
LordAshes.CharacterSheetsPlugin.Show (CreatureGuid cid) (at <e185359ca6b6474ca99ace0b7cad61ef>:0)
LordAshes.CharacterSheetsPlugin.Update () (at <e185359ca6b6474ca99ace0b7cad61ef>:0)
```

**Comment by LordAshes** [comment]
> I am having an issue where I cannot create a character sheet from in game.

That is an issue but it is a user issue and not a plugin issue ;-)
Character Sheet does not support the creation of character sheets in game.
You create the character sheets before the game and then view them (and
roll from them) in game.
As per the documentation, CTRL+I is to change the edition (the file prefix)
which allows you to have character sheets for different game systems.
CTRL+O is used for opening the character sheet. This will only work if
there is a CHS file matching the mini's name. BTW, next time attach your
logs (not a screen shot or text copy of the error message).

Best Regards,

Lord Ashes

**Comment by GreatKingCody** [comment]
It's funny, right after I posted this I created a sheet using the files available and it worked. Thanks for the response mate!
